name: algarve_wedding
description: Wedding in Portugal App

version: 2.0.14+80

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  lottie: ^1.1.0
  carousel_slider: ^4.0.0
  fluttericon: ^2.0.0
  image_viewer: ^1.5.0
  video_player: ^2.1.10
  simple_animations: ^2.4.2
  flutter_countdown_timer: ^4.1.0
  expandable: ^5.0.1
  firebase_core: ^1.3.0
  firebase_database: ^7.1.1
  firebase_remote_config: ^0.10.0+5
  firebase_storage: ^9.0.0
  firebase_auth: ^2.0.0
  cached_network_image: ^3.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  assets_audio_player: ^3.0.3+6
  flutter_automation: ^2.0.0
  multi_image_picker2: ^5.0.2
  cloud_firestore: ^2.5.1
  image_picker: ^0.8.4
  transparent_image: ^2.0.0
  package_info_plus: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/

  fonts:
    - family: Roboto Regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: Roboto Light
      fonts:
        - asset: fonts/Roboto-Light.ttf

    - family: Amatic Regular
      fonts:
        - asset: fonts/AmaticSC-Regular.ttf

    - family: Amatic Bold
      fonts:
        - asset: fonts/AmaticSC-Bold.ttf

    - family:  CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

    - family:  Neon
      fonts:
        - asset: fonts/Neon.ttf

    - family:  Beon
      fonts:
        - asset: fonts/Beon.otf